- .github/workflows/build.yml
pull requests were deploying to the docs, this should prevent that
> Prevent pull requests from building docs

- README.md
- docs/index.md
- docs/modules/date/SafeDate.ts.md
- docs/modules/number/Int.ts.md
- docs/modules/number/Natural.ts.md
- docs/modules/number/NegativeInt.ts.md
- docs/modules/number/PositiveInt.ts.md
- docs/modules/string/ASCII.ts.md
- docs/modules/string/EmailAddress.ts.md
- docs/modules/string/ISODateString.ts.md
- docs/modules/string/IntString.ts.md
- docs/modules/string/NaturalString.ts.md
- docs/modules/string/NegativeIntString.ts.md
- docs/modules/string/NonemptyString.ts.md
- docs/modules/string/PositiveIntString.ts.md
- docs/modules/string/UUID.ts.md
* re-generate docs
* docs: add ASCII
* update readme: add note about `docs-ts`
> Merge master > main

- docs/modules/string/ASCII.ts.md
- docs/modules/string/UUID.ts.md
- src/string/ASCII.ts
- src/string/UUID.ts
This is an experiment, just wondering how the docs looks if we add links to the modules that inspired them.
> Add links in docs

- README.md
- src/string/BtcAddress.ts
- test-utils/index.ts
- tests/BtcAddress.test.ts
> Add BtcAddress string module

- src/number/PositiveFloat.ts
- tests/PositiveFloat.test.ts
> Add PositiveFloat number module

- src/string/PositiveFloatString.ts
- tests/PositiveFloatString.test.ts
> Add PositiveFloat string module

- src/Decoder.ts
- src/Eq.ts
- src/Guard.ts
- src/SchemableExt.ts
- src/TaskDecoder.ts
- src/Type.ts
- src/number/Int.ts
- src/number/NonNegativeFloat.ts
- src/number/PositiveFloat.ts
- src/string/IntString.ts
- src/string/NaturalString.ts
- src/string/NegativeIntString.ts
- src/string/NonNegativeFloatString.ts
- src/string/PositiveFloatString.ts
- src/string/PositiveIntString.ts
- tests/NonNegativeFloat.test.ts
- tests/NonNegativeFloatString.test.ts
- tests/PositiveFloat.test.ts
- tests/PositiveFloatString.test.ts
> Add NonNegativeFloat and NonNegativeFloatString

- src/Decoder.ts
- src/Eq.ts
- src/Guard.ts
- src/SchemableExt.ts
- src/TaskDecoder.ts
- src/Type.ts
- src/string/JWT.ts
- tests/JWT.test.ts
Closes #9
This one is just a direct copy from the `validator.js` module.
> Add JWT module

- src/internal/EncoderBase.ts
- tests/UUID.test.ts
- tests/internal.EncoderBase.test.ts
Closes #65 
Brings coverage back up to 100%
> [#65] Add internal > EncoderBase.ts + UUID tests, add missing boolean combinator

- src/internal/util.ts
- tests/Arbitrary.test.ts
- tests/internal.util.test.ts
Brings coverage back up to 100%
> chore: add Arbitrary / util tests

- src/string/HslColor.ts
> Fix `HslColor` example comment

- CHANGELOG.md
- README.md
- docs/index.md
> [#83] Add changelog

- src/string/RGB.ts
- tests/string/RGB.test.ts
> [#7] Add RGB string module

- src/string/BigIntString.ts
- src/string/NaturalString.ts
- tests/string/BigIntString.test.ts
> [#88] Add BigIntString string module

- test-utils/index.ts
- tests/internal.util.test.ts
- tests/string/ASCII.test.ts
- tests/string/EmailAddress.test.ts
- tests/string/UUID.test.ts
> [#36] Replace older tests with validator.js test cases

- scripts/generate-schemables.ts
- src/Arbitrary.ts
- src/Decoder.ts
- src/Encoder.ts
- src/Eq.ts
- src/Guard.ts
- src/SchemableExt.ts
- src/TaskDecoder.ts
- src/Type.ts
- src/internal/ArbitraryBase.ts
- src/internal/EncoderBase.ts
- src/internal/Schemable2.ts
> [#108] feat: create WithUnknownContainers2 for EncoderBase

- src/PatternBuilder.ts
- src/internal/SchemaBase.ts
- src/internal/Schemable2.ts
- tests/PatternBuilder.test.ts
- tests/internal.ArbitraryBase.test.ts
- tests/internal.EncoderBase.test.ts
- tests/internal.SchemaBase.test.ts
> [#115] Add SchemaBase

- src/internal/SchemaBase.ts
- tests/internal.SchemaBase.test.ts
> [#123] Add brand / pattern to SchemaBase

- src/PatternBuilder.ts
- tests/PatternBuilder.test.ts
> [#128] New patterns

- src/date/safeDate.ts
- src/generic/mapFromEntries.ts
- src/generic/optionFromExclude.ts
- src/generic/optionFromNullable.ts
- src/generic/optionFromUndefined.ts
- src/internal/SchemaBase.ts
- src/number/float.ts
- src/number/floatFromString.ts
- src/number/int.ts
- src/number/intFromString.ts
- src/string/base64.ts
- tests/date/safeDate.test.ts
- tests/generic/mapFromEntries.test.ts
- tests/generic/optionFromExclude.test.ts
- tests/generic/optionFromNullable.test.ts
- tests/generic/optionFromUndefined.test.ts
- tests/number/float.test.ts
- tests/number/floatFromString.test.ts
- tests/number/int.test.ts
- tests/number/intFromString.test.ts
- tests/string/base64.test.ts
> [#109] Backfill schemas to schemables

- src/schemata/date/DateFromInt.ts
- src/schemata/date/DateFromUnixTime.ts
- src/schemata/number/Natural.ts
- src/schemata/number/NegativeFloat.ts
- src/schemata/number/NegativeInt.ts
- src/schemata/number/NonNegativeFloat.ts
- src/schemata/number/NonPositiveFloat.ts
- src/schemata/number/NonPositiveInt.ts
- src/schemata/number/PositiveFloat.ts
- src/schemata/number/PositiveInt.ts
- src/schemata/string/Ascii.ts
- src/schemata/string/BitcoinAddress.ts
- src/schemata/string/EmailAddress.ts
- src/schemata/string/HexColor.ts
- src/schemata/string/Hexadecimal.ts
Adds `S` types to all Schemata, and adds JsDoc to both internal type and Schema
> [no-ticket] adjust schemata jsdocs

- package.json
- src/DecodeError.ts
- src/SchemaExt.ts
- src/schemata.ts
- src/schemata/string/CreditCard.ts
- tests/DecodeError.test.ts
Closes #215 
Also bumps `package.json` version
> [#215]  Add Error Helpers

- package.json
- scripts/generate-schemata.ts
- src/Arbitrary.ts
- src/Decoder.ts
- src/Encoder.ts
- src/Eq.ts
- src/Guard.ts
- src/SchemableExt.ts
- src/TaskDecoder.ts
- src/Type.ts
- src/schemables/WithJson/definition.ts
- src/schemables/WithJson/instances/arbitrary.ts
- src/schemables/WithJson/instances/decoder.ts
- src/schemables/WithJson/instances/encoder.ts
- src/schemables/WithJson/instances/eq.ts
- src/schemables/WithJson/instances/guard.ts
- src/schemables/WithJson/instances/schema.ts
- src/schemables/WithJson/instances/task-decoder.ts
- src/schemables/WithJson/instances/type.ts
- src/schemata.ts
- src/schemata/json/JsonFromString.ts
- src/schemata/number/BigIntFromString.ts
- src/schemata/number/FloatFromString.ts
- src/schemata/number/IntFromString.ts
- test-utils/schemable-exports/WithJson.ts
- tests/schemables/WithJson.json.test.ts
- tests/schemables/WithJson.jsonString.test.ts
- tests/schemata/json/JsonFromString.test.ts
> [#11] Add WithJson

- package.json
- src/schemata.ts
- src/schemata/generic/NonEmptyArray.ts
- tests/schemata/generic/NonEmptyArray.test.ts
> [#163] Add `NonEmptyArray` generic schema

- src/Arbitrary.ts
- src/Decoder.ts
- src/Encoder.ts
- src/Eq.ts
- src/Guard.ts
- src/JsonSchema.ts
- src/Printer.ts
- src/SchemableExt.ts
- src/TaskDecoder.ts
- src/Type.ts
- src/schemables/WithUnknown/definition.ts
- src/schemables/WithUnknown/instances/arbitrary.ts
- src/schemables/WithUnknown/instances/decoder.ts
- src/schemables/WithUnknown/instances/encoder.ts
- src/schemables/WithUnknown/instances/eq.ts
- src/schemables/WithUnknown/instances/guard.ts
- src/schemables/WithUnknown/instances/json-schema.ts
- src/schemables/WithUnknown/instances/printer.ts
- src/schemables/WithUnknown/instances/schema.ts
- src/schemables/WithUnknown/instances/task-decoder.ts
- src/schemables/WithUnknown/instances/type.ts
- src/schemata.ts
- tests/schemables/WithUnknown.test.ts
> [#248] Add Unknown Schema

- src/schemables/WithRefine/instances/encoder.ts
- tests/schemables/WithRefine.test.ts
> [#250] fix encoder refinement bug

- src/schemata.ts
- src/schemata/generic/SetFromArray.ts
- tests/schemata/generic/SetFromArray.test.ts
> [#164] add set from array

- README.md
Added description of S.Annotate to README file
> docs: annotate
